name: Auto-merge Exercism Solutions

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'exercism-solutions-syncer[bot]'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Auto-merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr merge $PR_NUMBER --squash --delete-branch
